### ISSUE TITLE
Your Release of A3XAI AI won't die

### ISSUE THREAD

**Issue by VileAce** [kuplion/A3XAI#1]
Have you seen an issue where some of the AI and vehicles spawned by A3XAI can not be damaged.  It seems to be installed correctly.

 1:38:50 "[A3XAI Monitor] [Uptime:00:16:07][FPS:48][Groups:9/9][Respawn:1][HC:false]"
 1:38:50 "[A3XAI Monitor] [Static:3][Dynamic:0][Random:13][Air:2][Land:2][UAV:0][UGV:2]"
No errors in the RPT.

It does not happen to every unit.  I am trying to figure out exactly which ones and level AI it is happening to, but it does not appear to be a specific level or vehicle.

**Comment by kuplion** [comment]
This issue was fixed a long time ago on the ExileMod forums, before this was ever uploaded. Are you using the version from this repo?

**Comment by VileAce** [comment]
Yes,  I'm using the version from here.  I will review the forums and reinstall from here and see if it gets fixed.  It is just strange that it is sporadic when it happens.
